//requestAnimationFrame (gist.github.com/paulirish/1579671), addEventListener (mozilla), Array EM5 github.com/plusdude/array-generics, ClassList (eligrey 2014-01-31)
(function(){for(var e=0,b=["ms","moz","webkit","o"],a=0;a<b.length&&!window.requestAnimationFrame;++a)window.requestAnimationFrame=window[b[a]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[b[a]+"CancelAnimationFrame"]||window[b[a]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(a,b){var c=(new Date).getTime(),d=Math.max(0,16-(c-e)),f=window.setTimeout(function(){a(c+d)},d);e=c+d;return f});window.cancelAnimationFrame||(window.cancelAnimationFrame= function(a){clearTimeout(a)})})();
(function(){Event.prototype.preventDefault||(Event.prototype.preventDefault=function(){this.returnValue=!1});Event.prototype.stopPropagation||(Event.prototype.stopPropagation=function(){this.cancelBubble=!0});if(!Element.prototype.addEventListener){var f=[],d=function(b,e){var g=this,a=function(a){a.target=a.srcElement;a.currentTarget=g;e.handleEvent?e.handleEvent(a):e.call(g,a)};if("DOMContentLoaded"==b){var d=function(b){"complete"==document.readyState&&a(b)};document.attachEvent("onreadystatechange",d);f.push({object:this,type:b,listener:e,wrapper:d});if("complete"==document.readyState){var c=new Event;c.srcElement=window;d(c)}}else this.attachEvent("on"+b,a),f.push({object:this,type:b,listener:e,wrapper:a})},c=function(b,d){for(var c=0;c<f.length;){var a=f[c];if(a.object==this&&a.type==b&&a.listener==d){"DOMContentLoaded"==b?this.detachEvent("onreadystatechange",a.wrapper):this.detachEvent("on"+b,a.wrapper);break}++c}};Element.prototype.addEventListener=d;Element.prototype.removeEventListener=c;HTMLDocument&&(HTMLDocument.prototype.addEventListener=d,HTMLDocument.prototype.removeEventListener=c);Window&&(Window.prototype.addEventListener=d,Window.prototype.removeEventListener=c)}})();
(function(h,r,m){function q(a){a=u(a);return a!==a?0:0===a||r===a||-r===a?a:(0<a||-1)*l.floor(l.abs(a))}function v(a,c){var b,e,d,f,h;e=k(this);d=e.length>>>0;m!==a?(a=q(a),f=0>a?l.max(d+a,0):l.min(a,d)):f=0;m!==c&&(c=q(c),d=0>c?l.max(d+c,0):l.min(c,d));b=new g(d-f);for(h=0;f<d;++f,++h)f in e&&(b[h]=e[f]);return b}function w(a){return"[object Array]"===k.prototype.toString.call(a)}function n(a){if("[object Function]"!==k.prototype.toString.call(a))throw Error(a+" is not a function");}function s(a){if(!a)throw Error("reduce of empty array with no initial value"); }function x(a){var c=!0;if(g.prototype[a])try{g.prototype[a].call(m,/test/,null),c=!1}catch(b){}else c=!1;return c}function t(a){var c=!0;if(g[a])try{g[a](m,/test/,null),c=!1}catch(b){}else c=!1;c||(g[a]=y(a))}function y(a){return function(c){var b;if(m===c||null===c)throw Error("Array.prototype."+a+" called on "+c);b=g.prototype.slice.call(arguments,1);return g.prototype[a].apply(c,b)}}var g=h.Array,k=h.Object,l=h.Math,u=h.Number;h={indexOf:function(a,c){var b,e,d;b=k(this);e=b.length>>>0;m!==c? (c=q(c),d=0>c?l.max(e+c,0):l.min(c,e)):d=0;for(;d<e;++d)if(d in b&&a===b[d])return d;return-1},lastIndexOf:function(a,c){var b,e;b=k(this);e=b.length>>>0;m!==c?(c=q(c),e=0>c?e-l.abs(c):l.min(c,e-1)):e-=1;for(;-1<e;--e)if(e in b&&a===b[e])return e;return-1},forEach:function(a,c){var b,e,d;b=k(this);n(a);e=b.length>>>0;for(d=0;d<e;++d)d in b&&a.call(c,b[d],d,b)},every:function(a,c){var b,e,d;b=k(this);n(a);e=b.length>>>0;for(d=0;d<e;++d)if(d in b&&!a.call(c,b[d],d,b))return!1;return!0},some:function(a, c){var b,e,d;b=k(this);n(a);e=b.length>>>0;for(d=0;d<e;++d)if(d in b&&a.call(c,b[d],d,b))return!0;return!1},filter:function(a,c){var b=[],e,d,f,g;e=k(this);n(a);d=e.length>>>0;for(f=g=0;f<d;++f)f in e&&a.call(c,e[f],f,e)&&(b[g++]=e[f]);return b},map:function(a,c){var b=[],e,d,f;e=k(this);n(a);d=e.length>>>0;for(f=0;f<d;++f)f in e&&(b[f]=a.call(c,e[f],f,e));return b},reduce:function(a,c){var b,e,d,f;b=k(this);n(a);e=m!==c;d=b.length>>>0;for(f=0;f<d;++f)f in b&&(e?c=a(c,b[f],f,b):(c=b[f],e=!0));s(e); return c},reduceRight:function(a,c){var b,e,d;b=k(this);n(a);e=m!==c;for(d=(b.length>>>0)-1;-1<d;--d)d in b&&(e?c=a(c,b[d],d,b):(c=b[d],e=!0));s(e);return c}};for(var p in h)h.hasOwnProperty(p)&&(x(p)||(g.prototype[p]=h[p]),t(p));g.isArray=g.isArray||w;"concat join slice pop push reverse shift sort splice unshift".split(" ").forEach(t);if(document)try{g.slice(document.childNodes)}catch(z){g.prototype.slice=v}})(this,1/0);
if("document" in self&&!("classList" in document.createElement("_"))){(function(j){"use strict";if(!("Element" in j)){return}var a="classList",f="prototype",m=j.Element[f],b=Object,k=String[f].trim||function(){return this.replace(/^\s+|\s+$/g,"")},c=Array[f].indexOf||function(q){var p=0,o=this.length;for(;p<o;p++){if(p in this&&this[p]===q){return p}}return -1},n=function(o,p){this.name=o;this.code=DOMException[o];this.message=p},g=function(p,o){if(o===""){throw new n("SYNTAX_ERR","An invalid or illegal string was specified")}if(/\s/.test(o)){throw new n("INVALID_CHARACTER_ERR","String contains an invalid character")}return c.call(p,o)},d=function(s){var r=k.call(s.getAttribute("class")||""),q=r?r.split(/\s+/):[],p=0,o=q.length;for(;p<o;p++){this.push(q[p])}this._updateClassName=function(){s.setAttribute("class",this.toString())}},e=d[f]=[],i=function(){return new d(this)};n[f]=Error[f];e.item=function(o){return this[o]||null};e.contains=function(o){o+="";return g(this,o)!==-1};e.add=function(){var s=arguments,r=0,p=s.length,q,o=false;do{q=s[r]+"";if(g(this,q)===-1){this.push(q);o=true}}while(++r<p);if(o){this._updateClassName()}};e.remove=function(){var t=arguments,s=0,p=t.length,r,o=false;do{r=t[s]+"";var q=g(this,r);if(q!==-1){this.splice(q,1);o=true}}while(++s<p);if(o){this._updateClassName()}};e.toggle=function(p,q){p+="";var o=this.contains(p),r=o?q!==true&&"remove":q!==false&&"add";if(r){this[r](p)}return !o};e.toString=function(){return this.join(" ")};if(b.defineProperty){var l={get:i,enumerable:true,configurable:true};try{b.defineProperty(m,a,l)}catch(h){if(h.number===-2146823252){l.enumerable=false;b.defineProperty(m,a,l)}}}else{if(b[f].__defineGetter__){m.__defineGetter__(a,i)}}}(self))};

//Framework
hooks = {};
var Razko = { 
	get: function(tag,el){for(var el=el||document.querySelectorAll(tag), i = el.length,a = [];i--;){a[i] = el[i];}return a;},
	on: function(t,fn){for(var i, t = t.split(' '); i = t.pop();){(hooks[i] = hooks[i] || []).push(fn);}},
	fire: function(e){if(hooks[(e=e.type?e:{type:e}).type])hooks[e.type].forEach(function(fn){fn(e)})}
}

Razko.on('dom', function(){
	var counter = 0, items = Razko.get('.slideshow li');
	Razko.on('click keydown timer', function(e){
		if(e.type !== 'timer'){
			if(e.target.className === 'next' || e.keyCode === 39)counter++;
			if(e.target.className === 'prev' || e.keyCode === 37)counter--;
		}
		var itemToShow = Math.abs(counter%items.length);
		items.forEach(function(e){e.classList.remove('show')});
		items[itemToShow].classList.add('show');
	});
	setInterval(function(){counter++;Razko.fire('timer')}, 3000);
});

//Initiate
document.addEventListener('DOMContentLoaded', function(){Razko.fire('dom')});
window.addEventListener('load', function(){Razko.fire('load')});
document.addEventListener('click', (function(e){for(var el=e.target;el;el=el.parentNode)if(el.href)e.link=el;Razko.fire(e)}));
document.addEventListener('keydown', (function(e){for(var el=e.target;el;el=el.parentNode)if(el.href)e.link=el;Razko.fire(e)}));

